/**
 * Author:  davide
 * Created: May 12, 2017
 */
/*
    username: dCurre
    password: 1234
*/

/* CREAZIONE DELLA TABELLA UTENTI */
CREATE TABLE UTENTI (ID INTEGER DEFAULT GENERATED_BY_DEFAULT  NOT NULL GENERATED ALWAYS AS IDENTITY, NOME VARCHAR(256), COGNOME VARCHAR(256), EMAIL VARCHAR(256) NOT NULL, PASSWORD VARCHAR(256) NOT NULL, URLFOTOPROFILO VARCHAR(256), FRASEPERSONALE VARCHAR(256), PRIMARY KEY (ID));

/* -Creazione degli utenti statici */
INSERT INTO DCURRE.UTENTI (NOME, COGNOME, EMAIL, PASSWORD, URLFOTOPROFILO, FRASEPERSONALE) 
	VALUES ('Davide', 'Curreli', 'davidecurreli@mail.com', '123', '../img/fotoProfilo1.jpg', 'Welà');
INSERT INTO DCURRE.UTENTI (NOME, COGNOME, EMAIL, PASSWORD, URLFOTOPROFILO, FRASEPERSONALE) 
	VALUES ('Gigi', 'Serreli', 'ggserreli@mail.com', '123', '../img/fotoProfilo2.jpg', 'Ciaoo');
INSERT INTO DCURRE.UTENTI (NOME, COGNOME, EMAIL, PASSWORD, URLFOTOPROFILO, FRASEPERSONALE) 
	VALUES ('Gesu', 'Cristo', 'camminosullacqua@mail.com', '123', '../img/gesuFoto.jpg', 'Che Papà sia con te!');
INSERT INTO DCURRE.UTENTI (NOME, COGNOME, EMAIL, PASSWORD, URLFOTOPROFILO, FRASEPERSONALE) 
	VALUES ('Andrea', 'Mutolo', 'andreamutolo@mail.com', '123', '../img/fotoProfilo3.jpg', 'We');
INSERT INTO DCURRE.UTENTI (NOME, COGNOME, EMAIL, PASSWORD, URLFOTOPROFILO, FRASEPERSONALE) 
	VALUES ('Incompleto', 'Prova', 'prova@mail.com', '123', '../img/fotoLandscapePost.jpg', NULL);


/* CREAZIONE DELLA TABELLA POSTTYPE */
CREATE TABLE POSTTYPE (ID INTEGER DEFAULT GENERATED_BY_DEFAULT  NOT NULL GENERATED ALWAYS AS IDENTITY, "NAME" VARCHAR(32), PRIMARY KEY (ID));

/* -Creazione dei tipi di post statici */
INSERT INTO DCURRE.POSTTYPE ("NAME") 
	VALUES ('TEXT');
INSERT INTO DCURRE.POSTTYPE ("NAME") 
	VALUES ('IMAGE');


/* CREAZIONE DELLA TABELLA POSTS */
CREATE TABLE POSTS (ID INTEGER DEFAULT GENERATED_BY_DEFAULT  NOT NULL GENERATED ALWAYS AS IDENTITY, AUTHOR INTEGER, CONTENT VARCHAR(1024), "TYPE" INTEGER, PRIMARY KEY (ID));

/* -Creazione post statici */
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (0, 'Frase a caso1', 1);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (1, '../img/fotoLandscapePost.jpg', 2);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (2, 'Sempre sia lodato', 1);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (3, 'Frase a caso2', 1);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (2, 'Alzati e cammina', 1);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (2, 'http://static.qnm.it/www/fotogallery/1200X0/195073/selfie-sosia-di-gesu.jpg', 2);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (3, '../img/fotoLandscapePost.jpg', 2);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (1, 'Frase a caso3', 1);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (0, '../img/fotoLandscapePost.jpg', 2);
INSERT INTO DCURRE.POSTS (AUTHOR, CONTENT, "TYPE") 
	VALUES (3, '../img/allegatoProfilo2.jpg', 2);


/* CREAZIONE DELLA TABELLA GRUPPI */
CREATE TABLE GRUPPI (ID INTEGER DEFAULT GENERATED_BY_DEFAULT  NOT NULL GENERATED ALWAYS AS IDENTITY, NOME VARCHAR(256), URLFOTOGRUPPO VARCHAR(256), PRIMARY KEY (ID));

/* -Creazione gruppi statici */
INSERT INTO DCURRE.GRUPPI (NOME, URLFOTOGRUPPO) 
	VALUES ('Gruppo A', 'img/fotoProfilo1.jpg');
INSERT INTO DCURRE.GRUPPI (NOME, URLFOTOGRUPPO) 
	VALUES ('Gruppo B', 'img/fotoProfilo2.jpg');
INSERT INTO DCURRE.GRUPPI (NOME, URLFOTOGRUPPO) 
	VALUES ('Gruppo C', 'img/fotoProfilo3.jpg');
